# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db3938254525b9fd57769e0ab2885bc51522e6f08ee886eae439134794624482393da506a28ab1a36c77938890c428829706b09d7716d2edaad290102026299f

test:
  secret_key_base: 26b9afeea7c9a520c79c1943b4446d5c4bdd099bfece5dcc784d11e03af565969a59b4dccfbc65fd15a311156910f84357f596bf94c29627555d5c20c526ea5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
